author: 欧俊 # 作者
description: 狐狸的后山
keyword: devops, net core, design
favicon: 

excerpt_link: Read more

menu:
 Home: /
 #Tags: /tags/
 #Archives: /archives/
 #Projects: /project/
 #About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: ojdev
gitment_repo: ojdev.github.io
gitment_oauth_id: dca53eef8ae37c6bcbb2
gitment_oauth_secret: 6999e3a7ae92f2f5146bda78d29f3ae6c0af7c38

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/2107833?s=400&v=4
  description: "The end is always near."
  weibo_username: luacloud
  #twitter_username: yanm1ng
  github_username: odev
  #zhihu_username: yummy1121
  #douban_username: yanm1ng
  #linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
