# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global user.email "me@oujun.work"
    - run: git config --global user.name "OuJun"
    - run: node --version
    - run: npm --version
    - run: npm install hexo-cli -g
    - run: npm install hexo-deployer-git --save
    - run: hexo clean
    - run: hexo g
    - run: hexo d
    - run: echo '==========================================================='
    - run: ls ./
    - run: echo '==========================================================='
    - run: ls ./public
