name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean
      uses: heowc/action-hexo@master
      with:
          args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
          args: generate
    - name: Deploy
      uses: heowc/action-hexo@master
      env:
        EMAIL: luacloud@gmail.com
        NAME: OuJun
      with:
          args: deploy
