name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_RUN_ID
        run: echo $GITHUB_RUN_ID
      - name: GITHUB_RUN_NUMBER
        run: echo $GITHUB_RUN_NUMBER
      - name: GITHUB_ACTION
        run: echo $GITHUB_ACTION
